### ISSUE TITLE
Update package versions

### ISSUE THREAD

**Issue by bindushree16** [dry-dock/u14#154]
https://github.com/Shippable/pm/issues/10583

packages | current version | update version | Link for latest releases |
-- | -- | -- |--
Git | 2.16.2 |no update |https://launchpad.net/~git-core/+archive/ubuntu/ppa
gcloud | 173.0.0-0 | 194.0.0|https://cloud.google.com/sdk/docs/release-notes
kubectl | 1.8.0 | 1.9.0|https://kubernetes.io/docs/imported/release/notes/
KOPS | 1.8.0 | 1.8.1|https://github.com/kubernetes/kops/releases
helm | v2.8.0 | v2.8.2 |https://github.com/kubernetes/helm/releases
doctl | 1.6.0| 1.7.2|https://github.com/digitalocean/doctl/releases/tag/v1.7.2
ansible | 2.3.0.0 | 2.4.3.0|https://github.com/ansible/ansible/releases?after=v2.5.0a1
boto | 2.46.1 | 2.48.0|http://boto.cloudhackers.com/en/latest/
boto3 | 1.5.15 | 1.6.16|https://github.com/boto/boto3/releases
apache-libcloud | 2.0.0 | 2.3.0|https://libcloud.apache.org/downloads.html
azure | 2.0.0 | 3.0.0|https://docs.microsoft.com/en-us/azure/app-service/azure-sdk-dotnet-release-notes-3-0
dopy | 0.3.7a | no update |https://pypi.python.org/pypi/dopy/0.3.7
terraform | 0.8.7 | 0.11.5|https://github.com/hashicorp/terraform/releases
packer | 1.1.0 | 1.2.2|https://www.packer.io/downloads.html
jfrog | 1.7.0 | 1.14.0|https://bintray.com/jfrog/jfrog-cli-go/jfrog-cli-windows-amd64#release
zip | -| 3.0|https://packages.ubuntu.com/xenial/zip

Task

1. No update for git version form drydock/u14:master image
2. update  gcloud version to 194.0.0  for drydock/u14:master image
3. update  kubectl version to 1.9.0  for drydock/u14:master image 
4. update  KOPS version to 1.8.1  for drydock/u14:master image
5. update helm  version to v2.8.2  for drydock/u14:master image
6. update  doctl  version to 1.7.2  for drydock/u14:master image
7. update  ansible version to 2.4.3.0  for drydock/u14:master image
8. update  boto version to 2.48.0  for drydock/u14:master image
9. update boto3  version to 1.6.16  for drydock/u14:master image
10. update apache-libcloud  version to 2.3.0  for drydock/u14:master image
11. update  azure version to 3.0.0  for drydock/u14:master image
12. No update for dopy  version form drydock/u14:master image
13. update  terraform version to 0.11.5  for drydock/u14:master image
14. update packer  version to 1.2.2  for drydock/u14:master image
15. update zip  version 3.0  for drydock/u14:master image

Test

1. verify that git 2.16.2  is printing correct version number in drydock/u14:master image
2. verify that gcloud 194.0.0 is printing correct version number in drydock/u14:master image
3. verify that kubectl 1.9.0 is printing correct version number in drydock/u14:master image
4. verify that KOPS 1.8.1 is printing correct version number in drydock/u14:master image
5. verify that helm v2.8.2  is printing correct version number in drydock/u14:master image
6. verify that doctl 1.7.2  is printing correct version number in drydock/u14:master image
7. verify that ansible 2.4.3.0 is printing correct version number in drydock/u14:master image
8. verify that boto 2.48.0 is printing correct version number in drydock/u14:master image
9. verify that boto3 1.6.16  is printing correct version number in drydock/u14:master image
10. verify that apache-libcloud 2.3.0  is printing correct version number in drydock/u14:master image
11. verify that azure 3.0.0  is printing correct version number in drydock/u14:master image
12. verify that dopy 0.3.7a is printing correct version number in drydock/u14:master image
13. verify that terraform 0.11.5  is printing correct version number in drydock/u14:master image
14. verify that packer 1.2.2  is printing correct version number in drydock/u14:master image
15. verify that zip 3.0 is printing correct version number in drydock/u14:master image

**Comment by ric03uec** [comment]
looks good

**Comment by bindushree16** [comment]
build is success

https://app.shippable.com/github/Shippable/jobs/x86_64_Ubuntu_14_04_prep/builds/5ac6fed054f7fe070052f0a7/console

**Comment by ric03uec** [comment]
we need a test case here before closing this

**Comment by bindushree16** [comment]
tested 

https://rcapp.shippable.com/github/bindushree16/jobs/u14base-test/builds/5ac72e073f695f0700f890c3/console

**Comment by ric03uec** [comment]
Looks good, closing
